import Head from 'next/head';

import {FaInstagram} from 'react-icons/fa'
import {FaFacebook} from 'react-icons/fa'
import {FaLinkedin} from 'react-icons/fa'

export default function Home() {
    return (
        <>
        <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
            <title>Workshop</title>
            <meta name="description" content="Generated by create next app,width=device-width" />
            <link rel="icon" href="/images/6.png" />
        </Head>
            <div className="landing">
                <div className="landing-left">
                    <div>
                        <h1>
                            Web Design.<br />
                            Android + iOS.<br />
                            Free Food.<br />
                        </h1>
                        <p>The one stop shop for all your needs.</p>
                        <FaInstagram className="icon" />
                        <FaFacebook className="icon" />
                        <FaLinkedin className="icon" />
                        <br />
                        <button className="primary-button">
                            <h4>Contact Us</h4>
                        </button>
                    </div>
                    </div>
                <div className="landing-right">
                    <img src="/images/1.png" width="50%" />
                </div>
                </div>
                <div className="landing1">
                
                <div className="landing-left1">
                <img src="/images/10.png" width="50%"/>
                    
                </div>

                <div className="landing-right1">
               < div>
                        <h1>
                             Day 1.
                        </h1>
                        <p>Let food be thy medicine and medicine be thy food.</p>
                        <p>Food is symbolic of love when words are inadequate.</p>
                        <p>One cannot think well, love well, sleep well, if one has not dined well.</p>
                        
                        <br />
                        <button className="primary-button1">
                            <h4>Learn more</h4>
                        </button>
                    </div>
                </div>
            </div>
            <div className="landing2">
                <div className="landing-left2">
                    <div>
                        <h1>
                        Day 2.
                        </h1>
                        <p>If more of us valued food and cheer and song above hoarded gold, it would be a merrier world.</p>
                        <p>There is no love sincerer than the love of food.</p>
                        <p>Food is not rational. Food is culture, habit, craving, and identity.</p>

                        <button className="primary-button1">
                            <h4>Learn more</h4>
                        </button>
                    </div>
                    </div>
                <div className="landing-right2">
                    <img src="/images/7.png" width="50%" />
                </div>
                </div>
                <div className="landing3">
                
                <div className="landing-left3">
                <img src="/images/8.png" width="50%"/>
                    
                </div>

                <div className="landing-right3">
               < div>
                        <h1>
                            Day 3.
                        </h1>
                        <p>Food is our common ground, a universal experience.</p>
                        <p>Food may be essential as fuel for the body, but good food is fuel for the soul.</p>
                        <p>Laughter is brightest in the place where food is.</p>
                        <br />
                        <button className="primary-button1">
                            <h4>Learn more</h4>
                        </button>
                    </div>
                </div>
            </div>
            <div className="landing4">
                <div className="landing-left4">
                    <div>
                        <h1>
                        Day 4.
                        </h1>
                        <p>Food for us comes from our relatives, whether they have wings or fins or roots.</p>
                           <p> That is how we consider food. Food has a culture. </p>
                            <p>It has a history. It has a story.It has relationships.</p>

                        <button className="primary-button1">
                            <h4>Learn more</h4>
                        </button>
                    </div>
                    </div>
                <div className="landing-right2">
                    <img src="/images/9.png" width="50%" />
                </div>
                </div>
            <div className="landing5">
                 <div className="landing-left5">
                    <div>
                        <h1>
                        Day 5.
                        </h1>
                        <p>A party without cake is just a meeting.</p>
                        <p>Everything you see I owe to spaghetti.</p>
                        <p>Ice cream is exquisite. What a pity it isn’t illegal.</p>
                    </div>
                 </div>
             <div>
                <div className="landing-right5">
                    <img src="/images/6.png" width="45%" />
                </div>
             </div>
             </div>
        </>
    )
}