import Head from 'next/head'

export default function Page1() {
  return (
    <div>
      <Head>
        <title>Page 1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="landing">
      <h1>      Please Go To Another Page ---<br /></h1>
      </div>
    </div>
  )
}